# Generated by Django 4.2.5 on 2023-09-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_alter_book_price_alter_book_rental_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rented',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
