# Generated by Django 4.2.5 on 2023-09-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_book_total_rented'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='total_rented',
            new_name='total_rental',
        ),
    ]
